const CarData = [
    {
        id: 1,
        picture: "http://pngimg.com/uploads/volvo/volvo_PNG52.png",
        brand: "Nissan",
        model: "Juke",
        year: 2010,
        fuel: "petrol", 
        mileage: 275000,
        bodyType: "hatchback", 
        price: 5600,
    },
    {
        id: 2,
        picture: "http://pngimg.com/uploads/nissan/nissan_PNG83.png",
        brand: "Volvo",
        model: "CX50",
        year: 2015,
        fuel: "diesel", 
        mileage: 76000,
        bodyType: "hatchback", 
        price: 8220,
    },
    {
        id: 3,
        picture: "http://pngimg.com/uploads/mazda/mazda_PNG127.png",
        brand: "Mazda",
        model: "CX-3",
        year: 2016,
        fuel: "diesel", 
        mileage: 59000,
        bodyType: "hatchback", 
        price: 9860,
    },
    {
        id: 4,
        picture: "http://pngimg.com/uploads/porsche/porsche_PNG10612.png",
        brand: "Porsche",
        model: "Panamera",
        year: 2019,
        fuel: "petrol", 
        mileage: 12500,
        bodyType: "sedan", 
        price: 15220,
    },
    {
        id: 5,
        picture: "https://pngimg.com/uploads/uaz/uaz_PNG61.png",
        brand: "UAZ",
        model: "Hunter",
        year: 2005,
        fuel: "petrol", 
        mileage: 377000,
        bodyType: "SUV", 
        price: 2220,
    },
    {
        id: 6,
        picture: "http://pngimg.com/uploads/skoda/skoda_PNG12368.png",
        brand: "Skoda",
        model: "Yeti",
        year: 2020,
        fuel: "diesel", 
        mileage: 3000,
        bodyType: "MPV", 
        price: 7890,
    },
    {
        id: 7,
        picture: "http://pngimg.com/uploads/mercedes/mercedes_PNG80138.png",
        brand: "Mercedes",
        model: "Vito",
        year: 2012,
        fuel: "diesel", 
        mileage: 28400,
        bodyType: "MPV", 
        price: 3500,
    },
    {
        id: 8,
        picture: "http://pngimg.com/uploads/lada/lada_PNG143.png",
        brand: "Lada",
        model: "Vesta",
        year: 2015,
        fuel: "petrol", 
        mileage: 189000,
        bodyType: "sedan", 
        price: 2700,
    },
    {
        id: 9,
        picture: "http://pngimg.com/uploads/honda/honda_PNG10329.png",
        brand: "Honda",
        model: "Fit",
        year: 2021,
        fuel: "hybrid", 
        mileage: 150,
        bodyType: "estate", 
        price: 8220,
    },
    {
        id: 10,
        picture: "http://pngimg.com/uploads/tesla_car/tesla_car_PNG21.png",
        brand: "Tesla",
        model: "model X",
        year: 2017,
        fuel: "electric", 
        mileage: 15000,
        bodyType: "SUV", 
        price: 13800,
    },


]


export default CarData;